name: Auto-Update Asset Metadata

on:
  push:
    paths:
      - '*-logos/**'
      - 'assets/**'
    branches: [ main ]
  pull_request:
    paths:
      - '*-logos/**'
      - 'assets/**'
    branches: [ main ]

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
    
    - name: Generate updated metadata
      run: |
        python generate_metadata.py
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet metadata/asset-inventory.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit updated metadata
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add metadata/asset-inventory.json
        git commit -m "Auto-update asset metadata

        🤖 Automatically generated metadata for new/changed assets
        
        Co-authored-by: GitHub Actions <actions@github.com>"
    
    - name: Push changes
      if: steps.changes.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}